[profile.default]
# solc = "0.8.24"
auto_detect_solc = true
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = []
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet-chain.linfra.xyz"
[profile.sepolia]
eth_rpc_url = "https://rpc.sepolia.org"
[profile.base.sepolia]
eth_rpc_url = "https://sepolia.base.org"
[etherscan]
base = { key = "${ETHERSCAN_API_KEY}", chain = "8453"}
base_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "84532" }
