// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBlacklistSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBlacklistSystem {
  function addToBlacklist(address value) external;

  function removeFromBlacklist(address value) external;

  function notInBlacklist(address value) external view returns (bool);
}
