// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICommissionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICommissionSystem {
  function pay(uint256 fid, uint256 amount) external;

  function withdraw(uint256 fid) external;

  function balance(uint256 fid) external view returns (uint256);
}
