// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Blacklist } from "./tables/Blacklist.sol";
import { Commission } from "./tables/Commission.sol";
